[build]
# Custom Docker images with proper build environment for native dependencies

[target.x86_64-unknown-linux-gnu]
dockerfile = "Dockerfile.cross-x86_64"

[target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile.cross-aarch64"

[build.env]
passthrough = [
    "RUST_LOG",
    "CARGO_TERM_COLOR",
]
