[package]
description = "Lumen node binary"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lumen"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "lumen"
path = "src/main.rs"

[dependencies]
# Core lumen crates
lumen-common = {path = "../../crates/common"}
lumen-node = {path = "../../crates/node"}
lumen-rollkit = {path = "../../crates/rollkit"}

# Reth CLI and core dependencies
reth-basic-payload-builder.workspace = true
reth-chainspec.workspace = true
reth-cli-util.workspace = true
reth-engine-local.workspace = true
reth-ethereum = {workspace = true, features = ["node", "cli", "pool"]}
reth-ethereum-cli.workspace = true
reth-ethereum-payload-builder.workspace = true
reth-node-builder.workspace = true
reth-payload-builder.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-trie-db.workspace = true

# Alloy dependencies
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true

# Core dependencies
clap = {workspace = true, features = ["derive", "env"]}
eyre.workspace = true
serde = {workspace = true, features = ["derive"]}
thiserror.workspace = true
tokio = {workspace = true, features = ["full"]}
tracing.workspace = true

[lints]
workspace = true

[features]
default = ["jemalloc"]

jemalloc = ["reth-cli-util/jemalloc", "reth-ethereum-cli/jemalloc"]
jemalloc-prof = ["reth-cli-util/jemalloc-prof"]
tracy-allocator = ["reth-cli-util/tracy-allocator"]

asm-keccak = ["reth-ethereum-cli/asm-keccak"]

dev = ["reth-ethereum-cli/dev", "reth-ethereum/arbitrary"]

min-debug-logs = ["tracing/release_max_level_debug"]
min-error-logs = ["tracing/release_max_level_error"]
min-info-logs = ["tracing/release_max_level_info"]
min-trace-logs = ["tracing/release_max_level_trace"]
min-warn-logs = ["tracing/release_max_level_warn"]
