# Runs E2E tests.

name: e2e

on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Build ev-reth
        run: |
          cargo build --profile release --locked --bin ev-reth

      - name: Run E2E tests
        run: |
          cargo nextest run \
            --locked \
            --workspace \
            -E "package(ev-tests)" \
            --no-capture
        env:
          RUST_LOG: debug

      - name: Run fee-redirect E2E test
        run: |
          cargo test \
            -p ev-tests \
            --lib \
            node_redirects_base_fee_and_preserves_burn_sink \
            -- --ignored --nocapture
        env:
          RUST_LOG: info
